---
# Configuration du nœud master
k3s_master_ip: "192.168.1.79"
k3s_extra_server_args: >-
  --disable traefik
  --disable servicelb
  --flannel-backend=vxlan
  --cluster-cidr=10.42.0.0/16
  --service-cidr=10.43.0.0/16
  --write-kubeconfig-mode=644 