---
- name: Set hostname
  hostname:
    name: "k3s-master"
  register: hostname_changed

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 k3s-master"
    regexp: '^127\.0\.1\.1'
    state: present

- name: Reboot if hostname changed
  reboot:
  when: hostname_changed.changed

- name: Install required packages
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "vm.swappiness", value: "0" }

- name: Create K3s config directory
  file:
    path: "{{ k8s_config_dir }}"
    state: directory
    mode: '0755'

- name: Install K3s on master
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    INSTALL_K3S_EXEC="server {{ k3s_extra_server_args }}" \
    sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 30

- name: Read node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store node token
  set_fact:
    k3s_node_token: "{{ node_token.content | b64decode }}"

- name: Wait for k3s.yaml
  wait_for:
    path: "{{ kubeconfig_path }}"
    timeout: 30

- name: Wait for API server
  wait_for:
    host: "{{ k3s_master_ip }}"
    port: 6443
    timeout: 300

- name: Copy kubeconfig locally
  fetch:
    src: "{{ kubeconfig_path }}"
    dest: "files/k3s.yaml"
    flat: yes
  ignore_errors: true 