---

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter module is loaded at boot
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes
    mode: '0644'

- name: Configure sysctl for Kubernetes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: true

- name: Create K3s config directory
  file:
    path: "{{ k8s_config_dir }}"
    state: directory
    mode: '0755'

- name: Install K3s on master
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    INSTALL_K3S_EXEC="server {{ k3s_extra_server_args }}" \
    sh -
  args:
    creates: /usr/local/bin/k3s

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 30

- name: Read node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store node token
  set_fact:
    k3s_node_token: "{{ node_token.content | b64decode }}"

- name: Wait for k3s.yaml
  wait_for:
    path: "{{ kubeconfig_path }}"
    timeout: 30

- name: Wait for API server
  wait_for:
    host: "{{ k3s_master_ip }}"
    port: 6443
    timeout: 300

- name: Copy kubeconfig locally
  fetch:
    src: "{{ kubeconfig_path }}"
    dest: "files/k3s.yaml"
    flat: yes
  ignore_errors: true 