---
# Playbook principal pour déployer le cluster K3s
# Tags disponibles :
#   - master    : Installation du nœud master K3s
#   - workers   : Installation des nœuds workers K3s
#   - addons    : Installation des addons Kubernetes (MetalLB, Ingress, etc.)
#   - cluster   : Installation complète du cluster (master + workers)
#   - nfs       : Configuration du serveur NFS
#   - all       : Installation complète (cluster + addons + nfs)
- name: Deploy K3s Cluster - Master Node
  hosts: master
  become: true
  tags: 
    - master
    - cluster
    - all
  roles:
    - k3s_master

- name: Propager le token K3s à tous les hôtes
  hosts: all
  gather_facts: false
  tasks:
    - set_fact:
        k3s_node_token: "{{ hostvars[groups['master'][0]]['k3s_node_token'] }}"

- name: Deploy K3s Cluster - Worker Nodes
  hosts: worker
  become: true
  tags: 
    - workers
    - cluster
    - all
  roles:
    - k3s_worker

- name: Configure NFS Server
  hosts: nfs
  become: true
  tags:
    - nfs
    - all
  roles:
    - nfs_server

- name: Deploy K3s Cluster - Kubernetes Addons
  hosts: master
  become: true
  tags: 
    - addons
    - all
  roles:
    - k8s_addons