---
# Playbook principal pour déployer le cluster K3s
# Tags disponibles :
#   - master    : Installation du nœud master K3s
#   - workers   : Installation des nœuds workers K3s
#   - addons    : Installation des addons Kubernetes (MetalLB, Ingress, etc.)
#   - network   : Configuration réseau uniquement
#   - cluster   : Installation complète du cluster (master + workers)
#   - all       : Installation complète (cluster + addons)

- name: Configure Network
  hosts: all
  become: true
  tags: 
    - network
  roles:
    - network

- name: Deploy K3s Cluster - Master Node
  hosts: master
  become: true
  tags: 
    - master
    - cluster
    - all
  roles:
    - k3s_master

- name: Deploy K3s Cluster - Worker Nodes
  hosts: worker
  become: true
  tags: 
    - workers
    - cluster
    - all
  roles:
    - k3s_worker

- name: Deploy K3s Cluster - Kubernetes Addons
  hosts: master
  become: true
  tags: 
    - addons
    - all
  roles:
    - k8s_addons 