- name: Installer K3S sur le master
  hosts: master
  become: yes
  tasks:
    - name: Installer curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Installer K3S
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        executable: /bin/bash

    - name: Attendre que le token soit généré
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        timeout: 30

    - name: Lire le token K3S
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token_data

    - set_fact:
        k3s_token: "{{ token_data.content | b64decode }}"

- name: Installer K3S agent sur les workers
  hosts: worker
  become: yes
  vars:
    master_ip: 192.168.1.18
  tasks:
    - name: Installer curl
      apt:
        name: curl
        state: present
        update_cache: yes
        
    - name: Installer K3S agent
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION={{ k3s_version }} \
        K3S_URL=https://{{ master_ip }}:6443 \
        K3S_TOKEN={{ hostvars['192.168.1.18']['k3s_token'] }} sh -
      args:
        executable: /bin/bash