---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_changed

- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }}"
    regexp: '^127\.0\.1\.1'
    state: present

- name: Reboot if hostname changed
  reboot:
  when: hostname_changed.changed

- name: Install required packages
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: true

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "vm.swappiness", value: "0" }

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION={{ k3s_version }} \
    K3S_URL=https://{{ k3s_master_ip }}:6443 \
    K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_node_token'] }} \
    INSTALL_K3S_EXEC="agent {{ k3s_extra_agent_args }}" \
    sh -
  args:
    creates: /usr/local/bin/k3s 